package Billing_System;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*; 
import java.awt.event.*;
import static java.lang.Thread.sleep;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.security.util.Length;
/**
 *
 * @author Deshitha Hansajith
 */
public class settings extends javax.swing.JFrame {
    Connection c = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
        c = DB.connecrDB();
        set_all();
    }
    
    private void set_all(){
        try{
            String sql = "select * from settings";
            pst = c.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                txt_header.setText(rs.getString("header"));
                txt_footer.setText(rs.getString("footer"));
            }
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
             e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmd_save = new javax.swing.JButton();
        txt_header = new javax.swing.JTextField();
        txt_footer = new javax.swing.JTextField();
        cmd_reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Header");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 95, 150, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Footer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 155, 150, 40));

        cmd_save.setBackground(new java.awt.Color(255, 0, 51));
        cmd_save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmd_save.setText("Save");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 312, 137, 59));

        txt_header.setBackground(new java.awt.Color(0, 0, 0));
        txt_header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_header.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 95, 299, 42));

        txt_footer.setBackground(new java.awt.Color(0, 0, 0));
        txt_footer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_footer.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 155, 299, 41));

        cmd_reset.setBackground(new java.awt.Color(51, 255, 51));
        cmd_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_reset.setText("Reset");
        cmd_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_resetActionPerformed(evt);
            }
        });
        jPanel1.add(cmd_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing_System/FormatFactory078-settings.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(250, 100, 641, 446);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_resetActionPerformed
        set_all();
    }//GEN-LAST:event_cmd_resetActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        try{ 
            String header = txt_header.getText();
            String footer = txt_footer.getText();
            int id = 1;
            String sql = "update settings set header = '"+header+"' , footer = '"+footer+"' where id = '"+id+"'" ;
            pst = c.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Updted Successfuly");
            dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmd_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_reset;
    private javax.swing.JButton cmd_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_footer;
    private javax.swing.JTextField txt_header;
    // End of variables declaration//GEN-END:variables
}
