package Billing_System;



import java.awt.EventQueue;
import java.sql.*;
import javax.swing.*; 
import java.awt.event.*;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Deshitha Hansajith
 */
public class updatecustome extends javax.swing.JFrame {
    Connection c = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    static String id;
    ArrayList name = new ArrayList();

    /**
     * Creates new form updatecustome
     */
    public updatecustome() {
        initComponents();
        c = DB.connecrDB();
        update_table();
        setautocomplete();
        cmd_delete.setVisible(false);
        cmd_update.setVisible(false);
    }
    
    public void setautocomplete(){
        try{
            String sql = "select * from customer" ;
            pst = c.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                System.out.println(rs.getString("firstname"));
                name.add(rs.getString("firstname"));
            }
        }catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
                 e.printStackTrace();
            }
        
        
    }
    
    public void autocomplete(String txt){
        System.out.println(txt);
        String complete ="";
        int start = txt.length();
        int last = txt.length();
        for(int i = 0;i<name.size();i++){
            if(name.get(i).toString().startsWith(txt)){
                complete = name.get(i).toString();
                System.out.println(complete);
                last = complete.length();
                break;
            }
        }
        if(last>start){
            txt_firstname.setText(complete);
            txt_firstname.setCaretPosition(last);
            txt_firstname.moveCaretPosition(start);
        }
    }
    
    private void update_table(){
        try{
            String sql = "select * from customer";
            pst = c.prepareStatement(sql);
            rs = pst.executeQuery();
            table_customer.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
             e.printStackTrace();
        }
     }
    
    private void get_select(){
        try{
            int row = table_customer.getSelectedRow();
            id = (table_customer.getModel().getValueAt(row, 0).toString());
            String sql = "select * from customer where customerid = '"+id+"' ";
            pst = c.prepareStatement(sql);
            rs = pst.executeQuery(); 
            cmd_delete.setVisible(true);
            cmd_update.setVisible(true);
            if(rs.next()){
                String add1 = rs.getString("firstname");
                txt_firstname.setText(add1);
                
                String add2 = rs.getString("lastname");
                txt_lastname.setText(add2);
                
                String add3 = rs.getString("nicnumber");
                txt_nicnumber.setText(add3);
                
                String add4 = rs.getString("telephone");
                txt_telephone.setText(add4);
                
                String add5 = rs.getString("address");
                txt_address.setText(add5);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
             e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_firstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_telephone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nicnumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmd_update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_customer = new javax.swing.JTable();
        cmd_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        txt_firstname.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telephone Number");

        txt_telephone.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        txt_telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_telephoneKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");

        txt_lastname.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        txt_nicnumber.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        txt_nicnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nicnumberKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIC Number");

        txt_address.setFont(new java.awt.Font("Square721 Ex BT", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txt_telephone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nicnumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_firstname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_lastname, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nicnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing_System/FormatFactory002-group.png"))); // NOI18N

        cmd_update.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        cmd_update.setText("Update Information");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 0, 36), new java.awt.Color(204, 0, 255))); // NOI18N

        table_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_customerMouseClicked(evt);
            }
        });
        table_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_customerKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_customer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        cmd_delete.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        cmd_delete.setText("Delete Customer");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 146, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmd_delete)
                                .addGap(18, 18, 18)
                                .addComponent(cmd_update))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_update, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        setBounds(150, 50, 898, 661);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        try{
            String firstname = txt_firstname.getText();
            String lastname = txt_lastname.getText();
            String nicnumber = txt_nicnumber.getText();
            String telephone = txt_telephone.getText();
            String address = txt_address.getText();
            
            String sql = "update customer set firstname = '"+firstname+"' , lastname = '"+lastname+"' , nicnumber = '"+nicnumber+"'  ,address = '"+address+"' , telephone = '"+telephone+"' where customerid = '"+id+"'" ;
            pst = c.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Updted Successfuly");
            txt_firstname.setText("");
            txt_lastname.setText("");
            txt_nicnumber.setText("");
            txt_telephone.setText("");
            txt_address.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
        update_table();
    }//GEN-LAST:event_cmd_updateActionPerformed

    
    
    private void table_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_customerMouseClicked
        get_select();
    }//GEN-LAST:event_table_customerMouseClicked

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        int p = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p == 0){
            try{
                String sql = "delete from customer where customerid = ? ";
                pst = c.prepareStatement(sql);
                pst.setString(1,id);
                pst.execute(); 
                JOptionPane.showMessageDialog(null, "Deleted Successfuly");
                txt_firstname.setText("");
                txt_lastname.setText("");
                txt_nicnumber.setText("");
                txt_telephone.setText("");
                txt_address.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                 e.printStackTrace();
            }
            update_table();
        }
        
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void table_customerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_customerKeyReleased
        if((evt.getKeyCode()==KeyEvent.VK_UP) || (evt.getKeyCode()==KeyEvent.VK_DOWN)){
            get_select();
        }
    }//GEN-LAST:event_table_customerKeyReleased

    private void txt_firstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyReleased
//        String s = txt_firstname.getText();
//        StringBuilder builder = new StringBuilder(s);
//        char c1;
//        for(int i = 0;i<s.length();i++){
//            c1 = s.charAt(i);
//            if(Character.isDigit(c1)){
//                builder.deleteCharAt(i);
//                s = builder.toString();
//            }
//            if(Character.isUpperCase(c1)){
//                builder.deleteCharAt(i);
//                s = builder.toString();
//            }
//        }
//        txt_firstname.setText(s.toString());
    }//GEN-LAST:event_txt_firstnameKeyReleased

    private void txt_lastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyReleased
        String s = txt_lastname.getText();
        StringBuilder builder = new StringBuilder(s);
        char c1;
        for(int i = 0;i<s.length();i++){
            c1 = s.charAt(i);
            if(Character.isDigit(c1)){
                builder.deleteCharAt(i);
                s = builder.toString();
            }
            if(Character.isUpperCase(c1)){
                builder.deleteCharAt(i);
                s = builder.toString();
            }
        }
        txt_lastname.setText(s.toString());
    }//GEN-LAST:event_txt_lastnameKeyReleased

    private void txt_nicnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicnumberKeyReleased
        String s = txt_nicnumber.getText();
        StringBuilder builder = new StringBuilder(s);
        char c1;
        for(int i = 0;i<s.length();i++){
            c1 = s.charAt(i);
            
            if(Character.isUpperCase(c1)){
                builder.deleteCharAt(i);
                s = builder.toString();
            }
        }
        txt_nicnumber.setText(s.toString());
    }//GEN-LAST:event_txt_nicnumberKeyReleased

    private void txt_telephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telephoneKeyReleased
        String s = txt_telephone.getText();
        StringBuilder builder = new StringBuilder(s);
        char c1;
        for(int i = 0;i<s.length();i++){
            c1 = s.charAt(i);
            if(Character.isLowerCase(c1)){
                builder.deleteCharAt(i);
                s = builder.toString();
            }
            if(Character.isUpperCase(c1)){
                builder.deleteCharAt(i);
                s = builder.toString();
            }
        }
        txt_telephone.setText(s.toString());
    }//GEN-LAST:event_txt_telephoneKeyReleased

    private void txt_firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                txt_firstname.setText(txt_firstname.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable(){
                    @Override
                    
                 public void run(){
                     String txt = txt_firstname.getText();
                        autocomplete(txt);
                 }
                });
        }
    }//GEN-LAST:event_txt_firstnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatecustome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatecustome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatecustome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatecustome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatecustome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_customer;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_nicnumber;
    private javax.swing.JTextField txt_telephone;
    // End of variables declaration//GEN-END:variables
}
